pipeline {
    agent any

    triggers {
        cron('* * * * *') // Every minute
    }

    stages {
        stage('Show Current Time') {
            steps {
                echo "Current time is: ${new Date()}"
            }
        }
    }
}
