pipeline {
    agent any

    stages {
        stage('Parallel Tasks') {
            parallel {
                stage('Fast Task') {
                    steps {
                        bat 'ping -n 6 127.0.0.1 > nul'
                    }
                }
                stage('Slow Task') {
                    steps {
                        bat 'ping -n 16 127.0.0.1 > nul'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}