pipeline {
    agent any

    triggers {
        cron('* * * * *')  // every minute
    }

    stages {
        stage('Show Time') {
            steps {
                echo 'Current Time:'
                bat 'echo %TIME%'
            }
        }
    }
}
