pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/infuse-training-aug-2025/jenkins-session'
        GIT_BRANCH = 'Mahendra_Sinai_Priolkar'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }
        
        stage('Go to folder and run random number script') {
            steps {
                    bat '''
                    cd Exercise_1
                    randnum.bat
                    '''
            }
        }
    }
    
    post {
        always {
            echo 'Cleanup'
            deleteDir()
        }

        success {
            echo 'Build succeeded'
        }

        failure {
            echo 'Build failed'
        }
    }
}