pipeline {
    agent any

    stages {
        stage('Fast Task (~5 sec)') {
            steps {
                echo 'Running fast task...'
                bat 'ping -n 6 127.0.0.1 > nul'
                echo '✅ Fast task completed.'
            }
        }

        stage('Slow Task (~15 sec)') {
            steps {
                echo 'Running slow task'
                bat 'ping -n 16 127.0.0.1 > nul'
                echo '✅ Slow task completed.'
            }
        }
    }
}
